development:
  adapter: postgresql
  encoding: unicode
  database: ea_lunch_reservation_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ea_lunch_reservation_test
  pool: 5
  host: localhost
